[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'tomasr/molokai'
# hook_add = '''
#   let g:molokai_original = 1
#   let g:rehash256 = 1
#   colorscheme molokai
# '''

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
  colorscheme spring-night
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
hook_add = '''
function! PhpSyntaxOverride()
  hi! link phpDocTags phpDefine
  hi! link phpDocParam phpType
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END
'''

[[plugins]]
repo = 'StanAngeloff/php.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
# repo = 'leafgarland/typescript-vim'
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
# repo = 'jiangmiao/simple-javascript-indenter'
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'lumiliet/vim-twig'

[[plugins]]
repo = 'etaoins/vim-volt-syntax'
frozen = 1

[[plugins]]
repo = 'othree/html5.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
