[[plugins]]
repo = 'tani/vim-jetpack'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
opt = true

### Appearance ###
[[plugins]]
repo = 'akinsho/bufferline.nvim'
tag = 'v4.3.0'
on_event = 'VimEnter'
hook_post_source = """
lua << EOF
local bufferline = require('bufferline')
bufferline.setup({ options = {
  numbers = 'buffer_id',
  diagnostics = "nvim_lsp",
  indicator = { style = 'underline' },
}})
vim.keymap.set('n', '<Tab>', '<Cmd>BufferLineCycleNext<CR>', {})
vim.keymap.set('n', '<S-Tab>', '<Cmd>BufferLineCyclePrev<CR>', {})
EOF
"""

[[plugins]]
repo = 'ray-x/starry.nvim'
on_event = 'VimEnter'
hook_source = '''
let g:starry_disable_background = v:true
let g:starry_set_hl             = v:true
colorscheme monokai
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'VimEnter'
hook_add = "lua vim.opt.runtimepath:prepend(vim.fn.stdpath('data') .. '/treesitter')"
hook_post_source = '''
lua << EOF
require'nvim-treesitter.configs'.setup {
    parser_install_dir = vim.fn.stdpath('data') .. '/treesitter',
    auto_install = true,
    highlight = { enable = true, },
    indent = { enable = true, },
  }
EOF
'''

[[plugins]]
repo = 'brenoprata10/nvim-highlight-colors'
on_event = 'VimEnter'
hook_post_source = "lua require('nvim-highlight-colors').setup()"

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
tag = 'v2.20.7'
on_post_source = 'nvim-treesitter'
hook_post_source = '''
lua << EOF
require('indent_blankline').setup {
  show_current_context = true,
  show_current_context_start = true,
}
EOF
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
on_event = ['CursorMoved', 'CursorMovedI']
depends = 'nvim-treesitter'

### Extra Writing ###
[[plugins]]
## repo = 'windwp/nvim-autopairs'
repo = 'hrsh7th/nvim-insx'
on_event = 'InsertEnter'
hook_post_source = "lua require('insx.preset.standard').setup()"

[[plugins]]
repo = 'shinespark/vim-list2tree'
on_cmd = 'List2Tree'

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = 'MakeTable'

[[plugins]]
repo = 'inotom/str2htmlentity'
on_cmd = [ "Str2HtmlEntity", "Entity2HtmlString" ]

### Search ###
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = 'plenary.nvim'
tag = '0.1.2'
on_cmd = 'Telescope'
hook_add = 'nmap <Leader>f <Cmd>Telescope<CR>'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser'
hook_add = '''
nmap gw <Plug>(openbrowser-smart-search)
vmap gw <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'rhysd/devdocs.vim'
depends = 'open-browser.vim'
on_cmd = ['DevDocs', 'DevDocsUnderCursor', 'DevDocsALL', 'DevDocsALLUnderCursor']

[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
on_map = '<Plug>(git-messenger)'
hook_add = '''
nmap <Leader>gm <Plug>(git-messenger)
'''

### Filetype Specific Functions ###
# [[plugins]]
# repo = 'Shougo/context_filetype.vim'
# opt = true
# 
# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# on_event = ['CursorMoved', 'CursorMovedI']
# depends = 'context_filetype.vim'

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown', 'rst', 'mkd', 'md']
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = [ 'html', 'javascript', 'jsx', 'markdown', 'php', 'rescript', 'svelte', 'tsx', 'typescript', 'vue', 'xml' ]
on_event = 'InsertEnter'
depends = 'nvim-treesitter'
hook_source = "lua require('nvim-ts-autotag').setup()"

## Language Server Protocol ##
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ["BufReadPre", "BufNewFile"]

[[plugins]]
repo = 'j-hui/fidget.nvim'
tag = 'legacy'
on_post_source = 'nvim-lspconfig'
depends = 'nvim-lspconfig'
hook_post_source = "lua require('fidget').setup()"

[[plugins]]
repo = "hrsh7th/nvim-cmp"
on_event = ['CursorMoved', 'CursorMovedI']
depends = ['nvim-lspconfig', 'cmp-nvim-lsp']
hook_post_source = "lua require('my-cmp')"

[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"
on_post_source = 'nvim-cmp'
depends = 'nvim-lspconfig'

[[plugins]]
repo = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
on_post_source = 'nvim-lspconfig'
hook_source = """
lua << EOF
require('lsp_lines').setup()
vim.diagnostic.config({ virtual_text = false })
EOF
"""

## Sources for nvim-cmp ##
[[plugins]]
repo = "hrsh7th/cmp-path"
on_post_source = 'nvim-cmp'

[[plugins]]
repo = "hrsh7th/cmp-buffer"
on_post_source = 'nvim-cmp'

[[plugins]]
repo = "hrsh7th/cmp-cmdline"
on_post_source = 'nvim-cmp'

[[plugins]]
repo = 'octaltree/cmp-look'
on_post_source = 'nvim-cmp'

## Debug Adapter Protocol ##
[[plugins]]
repo = "mfussenegger/nvim-dap"

[[plugins]]
repo = "rcarriga/nvim-dap-ui"
depends = "nvim-dap"
hook_post_source = "lua require('my-dap')"

[[plugins]]
repo = "xdebug/vscode-php-debug"
opt = true
build = """
pnpm import
pnpm install --frozen-lockfile
pnpm run build
"""



# TODO: 今度試してみたい
# autosave
# toggle comments
# generate Document comment
# Debugger
# https://github.com/adoy/vim-php-refactoring-toolbox
# https://github.com/vim-php/vim-php-refactoring
# https://github.com/bling/vim-bufferline
# https://github.com/othree/yajs.vim
# https://github.com/dsawardekar/wordpress.vim
# https://github.com/hotwatermorning/auto-git-diff
# https://github.com/lukas-reineke/cmp-rg
# https://github.com/aduros/ai.vim
# https://github.com/mattn/vim-findroot
# https://github.com/nvim-treesitter/nvim-treesitter-textobjects
# https://daisuzu.hatenablog.com/entry/2020/12/03/003629  ## Quickfix
# https://zenn.dev/tmrekk/articles/4380961a754287  ## Quickfix
# https://github.com/ray-x/navigator.lua
# https://github.com/mfussenegger/nvim-dap
#
#[[plugins]]
#repo = "mxsdev/nvim-dap-vscode-js"
#depends = "mfussenegger/nvim-dap"
#hook_post_source = ""
#
#[[plugins]]
#repo = "microsoft/vscode-js-debug"
#opt = true
#build = """
#npm install --legacy-peer-deps
#npx gulp vsDebugServerBundle
#mv dist out
#"""
