# zmodload zsh/zprof && zprof
export EDITOR=nvim
export GHQ_ROOT=$(git config --global --get ghq.root)
export LSCOLORS=gxfxcxdxbxegedabagacad
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export ASDF_DATA_DIR=$XDG_DATA_HOME/asdf
export ASDF_CONFIG_FILE=$XDG_CONFIG_HOME/asdf/asdfrc
