bindkey -e

# load plugins
local sheldon_dump="$XDG_CACHE_HOME/sheldon-dump.sh"
if [ "$XDG_CONFIG_HOME/sheldon/plugins.toml" -nt $sheldon_dump ] || [ ! -e $sheldon_dump ]; then
  sheldon source > $sheldon_dump
fi
source $sheldon_dump

setopt hist_ignore_all_dups hist_save_no_dups # コマンド履歴の重複無視
setopt hist_no_store hist_ignore_space  # historyコマンドや行頭がスペースのコマンドは履歴に登録しない
setopt correct # スペルミス修正
setopt auto_pushd pushd_ignore_dups # cdでディレクトリスタックを積む
setopt list_packed # 補完候補をコンパクトに表示
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' # 大文字小文字を無視して補完/意図して大文字を入力した時は小文字の候補を補完しない

# homemade commands
take() {
  mkdir -p $1 && cd $1
}
alias ping='ping -c 5'
alias ls='ls -F --color=tty'
alias bubu='brew update && brew upgrade && \
  brew bundle dump --describe --global --force --formula --cask --tap --mas \
  & brew autoremove & brew cleanup'
zsh-defer unalias 'hgrep' # use rhysd/hgrep instead of common-aliases in ohmyzsh
alias reconnect='networksetup -SetAirportPower en0 off \
  && networksetup -SetAirportPower en0 on
'

# homemade commands that depends on smartctl(smartmontools)
alias temperature_sudo='smartctl -a /dev/disk0 | grep -i cel && sudo powermetrics -i 1 -n 1 --sampler smc,thermal'
# homemade commands that depends on smartctl(smartmontools) and osx-cpu-temp
alias temperature='smartctl -a /dev/disk0 | grep -i cel && echo "CPU Temp by osx-cpu-temp" && osx-cpu-temp'

# homemade commands that depends on ghq
repo(){
  cd $GHQ_ROOT/$(ghq list | peco --prompt '~/Repositories >' --select-1 --query ${1:-'github.com/'})
}
sandbox(){
  cd $GHQ_ROOT/sandbox
  target=$(ls | peco --prompt '~/sandbox >' --select-1 --query ${1:-' '})
  mkdir -pv ${target:-$1} && ls -lh && cd ${target:-$1}
}

# settings depends on plugins
# depends on mollifier/anyframe and peco
bindkey '^R' anyframe-widget-put-history
alias gs=anyframe-widget-checkout-git-branch
gbdel(){ # select git blanch and delete it.
  anyframe-source-git-branch -n \
  | anyframe-selector-auto \
  | awk '{print $1}' \
  | anyframe-action-execute git branch --delete
}
gsedit(){ # select file shown on git status and edit it.
  anyframe-source-git-status \
  | anyframe-selector-auto \
  | awk '{print $2}' \
  | anyframe-action-execute ${EDITOR}
}

# depends on romkatv/powerlevel10k
# To customize prompt, run `p10k configure` or edit p10k.zsh.
source ~/.config/p10k/p10k.zsh
