# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

bindkey -e
autoload -Uz compinit && compinit

# load plugins
eval "$(sheldon source)"

# homemade commands
take() {
  mkdir -p $1 && cd $1
}
alias ping='ping -c 5'
alias ls='ls -GF'
# homemade commands that depends on ghq
repo(){
  cd $GHQ_ROOT/$(ghq list | peco --prompt '~/Repositories >' --select-1 --query ${1:-'github.com/'})
}
sandbox(){
  cd $GHQ_ROOT/sandbox
  target=$(ls | peco --prompt '~/sandbox >' --select-1 --query ${1:-' '})
  mkdir -pv ${target:-$1} && ls -lh && cd ${target:-$1}
}

# settings depends on plugins
# depends on mollifier/anyframe and peco
bindkey '^R' anyframe-widget-put-history
alias gs=anyframe-widget-checkout-git-branch
gbdel(){ # select git blanch and delete it.
  anyframe-source-git-branch -n \
  | anyframe-selector-auto \
  | awk '{print $1}' \
  | anyframe-action-execute git branch --delete
}
gsedit(){ # select file shown on git status and edit it.
  anyframe-source-git-status \
  | anyframe-selector-auto \
  | awk '{print $2}' \
  | anyframe-action-execute ${EDITOR}
}

# depends on romkatv/powerlevel10k
# To customize prompt, run `p10k configure` or edit p10k.zsh.
source ~/.config/p10k/p10k.zsh
