bindkey -e

# load plugins
local sheldon_dump="$XDG_CACHE_HOME/sheldon-dump.sh"
if [ "$XDG_CONFIG_HOME/sheldon/plugins.toml" -nt $sheldon_dump ] || [ ! -e $sheldon_dump ]; then
  sheldon source > $sheldon_dump
fi
source $sheldon_dump

# homemade commands
take() {
  mkdir -p $1 && cd $1
}
alias ping='ping -c 5'
alias ls='ls -GF'
# homemade commands that depends on ghq
repo(){
  cd $GHQ_ROOT/$(ghq list | peco --prompt '~/Repositories >' --select-1 --query ${1:-'github.com/'})
}
sandbox(){
  cd $GHQ_ROOT/sandbox
  target=$(ls | peco --prompt '~/sandbox >' --select-1 --query ${1:-' '})
  mkdir -pv ${target:-$1} && ls -lh && cd ${target:-$1}
}

# settings depends on plugins
# depends on mollifier/anyframe and peco
bindkey '^R' anyframe-widget-put-history
alias gs=anyframe-widget-checkout-git-branch
gbdel(){ # select git blanch and delete it.
  anyframe-source-git-branch -n \
  | anyframe-selector-auto \
  | awk '{print $1}' \
  | anyframe-action-execute git branch --delete
}
gsedit(){ # select file shown on git status and edit it.
  anyframe-source-git-status \
  | anyframe-selector-auto \
  | awk '{print $2}' \
  | anyframe-action-execute ${EDITOR}
}

# depends on romkatv/powerlevel10k
# To customize prompt, run `p10k configure` or edit p10k.zsh.
source ~/.config/p10k/p10k.zsh
